### ISSUE TITLE
Add rule to SI Schema for long bio note entries

### ISSUE THREAD

**Issue by ebeshero** [DigitalMitford/DM_SiteIndex#4]
Add a Schematron rule to the SI ODD that tests `<note>` elements. Where these contain multiple paragraphs, assert that the string `"Mitford"`  must appear in the first paragraph. This helps to ensure that long bio notes (for entries like Elford and Talfourd) begin with a paragraph indicating how a named entity relates to MRM and her world.

**Comment by lmwilson** [comment]
Let's talk about this rule before we implement. I think this will be a good rule going forward but we have not really implemented it at all fully yet.--will that be a problem, until I have time to go in this summer and fix all those? I was going to work on that alongside reworking all the long bios. in order to output them more effectively on the site. (Marking off paragraphs, making sure paragraph one has all the essential info in it if that's all that shows in pop up box, etc.) Should I do that first?

**Comment by ebeshero** [comment]
The rule is really designed to guide the process—it can be implemented gently with blue or yellow highlights instead of red. It would just help flag entries that have multi paragraphs inside where the first does not contain the word, “Mitford”.

**Comment by ebeshero** [comment]
So I am in favor of implementing because it is designed specifically to help guide the revision process. Otherwise, why write a schema rule? I updated Talfourd’s entry already myself.

**Comment by ebeshero** [comment]
Implemented in current SI schema
